version: "3.0"

services:
  database:
    image: postgres
    container_name: pgDBIgnite
    restart: unless-stopped
    network_mode: host
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${PGDATA}:/var/lib/postgresql/data/pgdata

  # app:
  #   build: .
  #   container_name: rentalx
  #   restart: unless-stopped
  #   network_mode: host
  #   # ports:
  #   #   - 3000:3000
  #   volumes:
  #     - .:/usr/app
  #   depends_on:
  #     - database
