name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # - name: Setup Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 18
        
    # - name: Install Dependencies
    #   run: npm ci
      
    # - name: Build
    #   run: npm run build
      
    - name: Deploy project to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /home/app/rentalx
          git pull
          npm ci
          npm run build
          npx typeorm -d dist/infra/typeORM/database/DataSource.js migration:run
          pm2 restart rentalx-api
        
    # - name: Copy files to server
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     key: ${{ secrets.SSH_KEY }}
    #     port: ${{ secrets.SSH_PORT }}
    #     source: "."
    #     target: "test"
